apiVersion: v1
kind: Pod
metadata:
    name: hello-world-rest-api
    labels:
        app: hello-world-rest-api
spec:
    containers:
        - name: hello-world-rest-api
          image: anandsivaji/hello-world-rest-api:0.0.1-SNAPSHOT
