apiVersion: v1
kind: Pod
metadata:
    name: hello-world-rest-api
    labels:
        app: hello-world-rest-api
    namespace: default
spec:
    containers:
        - name: hello-world-rest-api
          image: anandsivaji/hello-world-rest-api:0.0.1-SNAPSHOT
          #ports:
          #   - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30186
  selector:
    app: hello-world-rest-api
  