apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-web-application
  name: todo-web-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-web-application
  template:
    metadata:
      labels:
        app: todo-web-application
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
#          value: todos
          valueFrom:
             configMapKeyRef:
                key: RDS_DB_NAME
                name: todo-web-app-config
        - name: RDS_HOSTNAME
          valueFrom:
             configMapKeyRef:
                key: RDS_HOSTNAME
                name: todo-web-app-config
#          value: mysql
        - name: RDS_PASSWORD
          valueFrom:
             secretKeyRef:
                key: RDS_PASSWORD
                name: todo-web-app-secret
        - name: RDS_PORT
#          value: "3306"
          valueFrom:
             configMapKeyRef:
                key: RDS_PORT
                name: todo-web-app-config
        - name: RDS_USERNAME
#          value: todos-user
          valueFrom:
             configMapKeyRef:
                key: RDS_USERNAME
                name: todo-web-app-config
        image: anandsivaji/todo-web-application-mysql:0.0.1-SNAPSHOT
        name: todo-web-application
        ports:
        - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-web-application
  name: todo-web-application
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: todo-web-application
